/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resutrant_s;
//package Viewers_s;
import account_s.account;
import setcost_s.setcost;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.math.BigDecimal;
import java.awt.Color;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import login_s.login;


/**
 *
 * @author user
 */
public class resutrants extends javax.swing.JFrame {
    setcost s=new setcost();
    double[] i=new double[5];
    String pMeal;
    String isubTotal;
    String itotal;
    String iTaxTotal;
    public double ChickBurgr;
    
    double cMeal;
    double firstnum;
    double secondnum;
    double result;
    String operation;
    
    
    
    public double idelivery;
    public double Nigerian_Naira=s.niger;
    public double Canadian_Dollar=s.canada;
    public double Indian_Rupee=s.india;
   public double Kenyan_shilling=45;
  public  double US_Dollar=s.usa;
  public  double Brazilian_Real=22.0;
  public  double philippine_peso=12.0;
  
  
  
  
  //Cost for Drinks in our application
  
  
    public    double Tea=s.tea;
    public    double Ice_Tea=4;
    public    double Coffee=s.coffee;
    public    double Ice_Coffee=2;
    public    double Cola=s.cola;
    public    double Coke=35.60;
    public    double Milk=s.milk;
    public    double Orange=96;
    
    
    
    
    
    //set cost meal
    public double iChiBuurger;
    public double iBCBuurger;
    public double iCheBuurger;
    
    
    

    /**
     * Creates new form resutrants
     */
    public resutrants() {
        initComponents();
        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbmeal = new javax.swing.JCheckBox();
        jcbburger = new javax.swing.JCheckBox();
        jcbcheese = new javax.swing.JCheckBox();
        jtxtmeal = new javax.swing.JTextField();
        jtxtbacon = new javax.swing.JTextField();
        jtxtburger = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCDelivery = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCmbDrink = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCbcountry = new javax.swing.JComboBox<>();
        jTextamount = new javax.swing.JTextField();
        jlblconvert = new javax.swing.JLabel();
        jbtnConvert = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jlblbirr = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jlblCostOfDrink = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblCostOfMeal = new javax.swing.JLabel();
        jlblCostOfDelivery = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jlbltax = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();
        jlblsubtotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jbtntotal = new javax.swing.JButton();
        jbtnreceipt = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnclose = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jTextDisplay = new javax.swing.JTextField();
        jbtn8 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnMult = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnDiv = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnPoint = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnMin = new javax.swing.JButton();
        jbtnDec = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnRnd = new javax.swing.JButton();
        jbtnMou = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtchicburg = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(null);

        jcbmeal.setBackground(new java.awt.Color(255, 0, 51));
        jcbmeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbmeal.setForeground(new java.awt.Color(51, 255, 255));
        jcbmeal.setText("Chiken Burger Meal");
        jcbmeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbmealMouseClicked(evt);
            }
        });
        jPanel1.add(jcbmeal);
        jcbmeal.setBounds(4, 66, 203, 36);

        jcbburger.setBackground(new java.awt.Color(255, 0, 0));
        jcbburger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbburger.setForeground(new java.awt.Color(51, 255, 255));
        jcbburger.setText("Chiken Burger");
        jcbburger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbburgerMouseClicked(evt);
            }
        });
        jcbburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbburgerActionPerformed(evt);
            }
        });
        jPanel1.add(jcbburger);
        jcbburger.setBounds(4, 12, 219, 36);

        jcbcheese.setBackground(new java.awt.Color(255, 0, 0));
        jcbcheese.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbcheese.setForeground(new java.awt.Color(51, 255, 255));
        jcbcheese.setText("Bacon Cheese Burger");
        jcbcheese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbcheeseMouseClicked(evt);
            }
        });
        jPanel1.add(jcbcheese);
        jcbcheese.setBounds(4, 120, 219, 36);

        jtxtmeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtmeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtmeal.setText("0");
        jtxtmeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(jtxtmeal);
        jtxtmeal.setBounds(342, 69, 136, 30);

        jtxtbacon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtbacon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtbacon.setText("0");
        jtxtbacon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(jtxtbacon);
        jtxtbacon.setBounds(342, 123, 136, 30);

        jtxtburger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtburger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtburger.setText("0");
        jtxtburger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.add(jtxtburger);
        jtxtburger.setBounds(342, 15, 136, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Drinks");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 160, 130, 33);

        jCDelivery.setBackground(new java.awt.Color(255, 0, 0));
        jCDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCDelivery.setForeground(new java.awt.Color(51, 255, 255));
        jCDelivery.setText("Home delivery");
        jCDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDeliveryActionPerformed(evt);
            }
        });
        jPanel1.add(jCDelivery);
        jCDelivery.setBounds(323, 194, 155, 34);

        jCheckBox5.setBackground(new java.awt.Color(255, 0, 0));
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(51, 255, 255));
        jCheckBox5.setText("Tax");
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBox5);
        jCheckBox5.setBounds(10, 194, 106, 34);

        jCmbDrink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCmbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Drink", "Tea", "Ice Tea", "Cofee", "Ice Cofee", "Milk", "Orange", "cola", "coke" }));
        jCmbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbDrinkActionPerformed(evt);
            }
        });
        jPanel1.add(jCmbDrink);
        jCmbDrink.setBounds(342, 169, 136, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/Haninbal.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 4, 510, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1, 75, 510, 240);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setLayout(null);

        jCbcountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCbcountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose country", "Nigeria", "Kenyan", "USA", "Canada", "Brazil", "Indian" }));
        jCbcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbcountryActionPerformed(evt);
            }
        });
        jPanel2.add(jCbcountry);
        jCbcountry.setBounds(101, 15, 271, 43);

        jTextamount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextamount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.add(jTextamount);
        jTextamount.setBounds(101, 81, 176, 54);

        jlblconvert.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblconvert.setForeground(new java.awt.Color(255, 255, 51));
        jlblconvert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblconvert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(jlblconvert);
        jlblconvert.setBounds(101, 141, 176, 40);

        jbtnConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnConvert.setText("Convert");
        jbtnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConvertActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnConvert);
        jbtnConvert.setBounds(14, 192, 122, 32);

        jbtnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnclear.setText("Clear");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnclear);
        jbtnclear.setBounds(304, 192, 132, 31);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Birr");
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(287, 81, 85, 49);

        jlblbirr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblbirr.setForeground(new java.awt.Color(51, 255, 51));
        jlblbirr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblbirr.setText("...");
        jlblbirr.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel2.add(jlblbirr);
        jlblbirr.setBounds(287, 141, 84, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/fresh_fruits-1920x1080.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 480, 280);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(516, 75, 480, 240);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel3.setLayout(null);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setText("Cost Of Meal");
        jPanel3.add(label5);
        label5.setBounds(14, 82, 172, 42);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(240, 240, 240));
        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setText("Cost Of Delivery");
        jPanel3.add(label6);
        label6.setBounds(14, 144, 172, 42);

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(240, 240, 240));
        label7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label7.setText("Cost Of Drink");
        jPanel3.add(label7);
        label7.setBounds(14, 22, 172, 42);

        jlblCostOfDrink.setBackground(new java.awt.Color(255, 255, 255));
        jlblCostOfDrink.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblCostOfDrink.setForeground(new java.awt.Color(255, 255, 51));
        jlblCostOfDrink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfDrink.setText("0");
        jlblCostOfDrink.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jlblCostOfDrink);
        jlblCostOfDrink.setBounds(215, 22, 190, 42);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel7);
        jLabel7.setBounds(250, 129, 4, 4);

        jlblCostOfMeal.setBackground(new java.awt.Color(255, 255, 255));
        jlblCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblCostOfMeal.setForeground(new java.awt.Color(255, 255, 51));
        jlblCostOfMeal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfMeal.setText("0");
        jlblCostOfMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jlblCostOfMeal);
        jlblCostOfMeal.setBounds(215, 82, 190, 42);

        jlblCostOfDelivery.setBackground(new java.awt.Color(255, 255, 255));
        jlblCostOfDelivery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblCostOfDelivery.setForeground(new java.awt.Color(255, 255, 51));
        jlblCostOfDelivery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCostOfDelivery.setText("0");
        jlblCostOfDelivery.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jlblCostOfDelivery);
        jlblCostOfDelivery.setBounds(215, 142, 190, 42);

        jLabel2.setBackground(new java.awt.Color(51, 255, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Birr");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel3.add(jLabel2);
        jLabel2.setBounds(415, 82, 76, 42);

        jLabel4.setBackground(new java.awt.Color(51, 255, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Birr");
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel3.add(jLabel4);
        jLabel4.setBounds(415, 142, 76, 42);

        jLabel5.setBackground(new java.awt.Color(51, 255, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Birr");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel3.add(jLabel5);
        jLabel5.setBounds(415, 22, 76, 42);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/80f0fff9b19edea4b8d417d427d9effd.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 0, 500, 260);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(2, 321, 500, 262);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel4.setLayout(null);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Sub-Total");
        jPanel4.add(label2);
        label2.setBounds(22, 22, 172, 42);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setText("Tax");
        jPanel4.add(label3);
        label3.setBounds(22, 74, 172, 42);

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setText("Total");
        jPanel4.add(label4);
        label4.setBounds(22, 126, 172, 42);

        jlbltax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbltax.setForeground(new java.awt.Color(0, 255, 204));
        jlbltax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbltax.setText("0");
        jlbltax.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbltax.setName("0"); // NOI18N
        jPanel4.add(jlbltax);
        jlbltax.setBounds(239, 74, 133, 42);

        jlbltotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbltotal.setForeground(new java.awt.Color(0, 255, 204));
        jlbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbltotal.setText("0");
        jlbltotal.setToolTipText("");
        jlbltotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jlbltotal);
        jlbltotal.setBounds(239, 126, 133, 42);

        jlblsubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblsubtotal.setForeground(new java.awt.Color(51, 255, 204));
        jlblsubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblsubtotal.setText("0");
        jlblsubtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jlblsubtotal);
        jlblsubtotal.setBounds(239, 22, 133, 42);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Birr");
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel4.add(jLabel6);
        jLabel6.setBounds(378, 22, 79, 42);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Birr");
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel4.add(jLabel8);
        jLabel8.setBounds(378, 126, 85, 42);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Birr");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));
        jPanel4.add(jLabel9);
        jLabel9.setBounds(378, 74, 85, 42);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/Galaxy_41.jpg"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(0, 0, 480, 260);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(517, 321, 480, 262);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel5.setLayout(null);

        jbtntotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtntotal.setText("Total");
        jbtntotal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtntotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtntotalMouseClicked(evt);
            }
        });
        jbtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntotalActionPerformed(evt);
            }
        });
        jPanel5.add(jbtntotal);
        jbtntotal.setBounds(117, 29, 112, 43);

        jbtnreceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnreceipt.setText("Receipt");
        jbtnreceipt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnreceiptActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnreceipt);
        jbtnreceipt.setBounds(366, 29, 112, 43);

        jbtnreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnreset);
        jbtnreset.setBounds(594, 29, 112, 43);

        jbtnclose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnclose.setText("Close");
        jbtnclose.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jbtnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncloseActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnclose);
        jbtnclose.setBounds(834, 29, 112, 43);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/paris.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(0, 0, 990, 120);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(2, 594, 990, 120);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel6.setLayout(null);

        jPanel11.setLayout(null);

        jTextDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel11.add(jTextDisplay);
        jTextDisplay.setBounds(0, 37, 319, 61);

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn8);
        jbtn8.setBounds(84, 157, 69, 57);

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn7);
        jbtn7.setBounds(5, 157, 69, 57);

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn9);
        jbtn9.setBounds(163, 157, 69, 57);

        jbtnMult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMult.setText("*");
        jbtnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnMult);
        jbtnMult.setBounds(250, 157, 69, 57);

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn4);
        jbtn4.setBounds(5, 232, 69, 57);

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn5);
        jbtn5.setBounds(84, 232, 69, 57);

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn6);
        jbtn6.setBounds(163, 232, 69, 57);

        jbtnDiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDiv.setText("/");
        jbtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnDiv);
        jbtnDiv.setBounds(250, 232, 69, 57);

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn1);
        jbtn1.setBounds(5, 307, 69, 57);

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn2);
        jbtn2.setBounds(84, 307, 69, 57);

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn3);
        jbtn3.setBounds(163, 307, 69, 57);

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnAdd.setText("+");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnAdd);
        jbtnAdd.setBounds(250, 307, 69, 57);

        jbtnPoint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPoint.setText(".");
        jbtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPointActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnPoint);
        jbtnPoint.setBounds(5, 382, 69, 57);

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel11.add(jbtn0);
        jbtn0.setBounds(84, 382, 69, 57);

        jbtnEqual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnEqual.setText("=");
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnEqual);
        jbtnEqual.setBounds(163, 382, 69, 57);

        jbtnMin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMin.setText("-");
        jbtnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMinActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnMin);
        jbtnMin.setBounds(250, 382, 69, 57);

        jbtnDec.setFont(new java.awt.Font("Wingdings", 1, 18)); // NOI18N
        jbtnDec.setText("█");
        jbtnDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnDec);
        jbtnDec.setBounds(5, 457, 69, 57);

        jbtnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnClear.setText("c");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnClear);
        jbtnClear.setBounds(84, 457, 69, 57);

        jbtnRnd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnRnd.setText("RD");
        jbtnRnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRndActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnRnd);
        jbtnRnd.setBounds(163, 457, 69, 57);

        jbtnMou.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMou.setText("%");
        jbtnMou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMouActionPerformed(evt);
            }
        });
        jPanel11.add(jbtnMou);
        jbtnMou.setBounds(250, 457, 69, 57);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/29ce9c6365b867435b9c5cc75c8ac4e6.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel11.add(jLabel15);
        jLabel15.setBounds(0, 4, 340, 590);

        jTabbedPane1.addTab("Calculator", jPanel11);

        jtxtchicburg.setColumns(20);
        jtxtchicburg.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jtxtchicburg.setRows(5);
        jtxtchicburg.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane1.setViewportView(jtxtchicburg);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Receipt", jPanel7);

        jPanel6.add(jTabbedPane1);
        jTabbedPane1.setBounds(4, 15, 340, 620);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/80f0fff9b19edea4b8d417d427d9effd.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(0, 10, 350, 570);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(1004, 76, 350, 640);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Edwardian Script ITC", 1, 48)); // NOI18N
        label1.setForeground(new java.awt.Color(204, 0, 204));
        label1.setName(""); // NOI18N
        label1.setText("Resturant Managment System");
        getContentPane().add(label1);
        label1.setBounds(210, 0, 880, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resutrant_s/Sun_Forrest_1920x1200_cool_twitter_backgrounds.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -20, 1380, 760);

        setBounds(0, 0, 1369, 758);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
          String enternumber = jTextDisplay.getText()+jbtn7.getText();
          jTextDisplay.setText(enternumber);

    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
          String enternumber = jTextDisplay.getText()+jbtn8.getText();
          jTextDisplay.setText(enternumber);

    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn9.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn4.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn5.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn6.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn1.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn2.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn3.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPointActionPerformed
        // TODO add your handling code here:
         String enternumber = jTextDisplay.getText()+jbtnPoint.getText();
        jTextDisplay.setText(".");
    }//GEN-LAST:event_jbtnPointActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        String enternumber = jTextDisplay.getText()+jbtn0.getText();
          jTextDisplay.setText(enternumber);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
               // TODO add your handling code here:
        String answer;
        secondnum=Double.parseDouble(jTextDisplay.getText());
        if(operation=="+")
        {
            result=firstnum+secondnum;
            answer=String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        else if(operation=="-")
        {
            result=firstnum-secondnum;
            answer=String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        
        else if(operation=="*")
        {
            result=firstnum*secondnum;
            answer=String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        
        else if(operation=="/")
        {
            result=firstnum/secondnum;
            answer=String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }
        else if(operation=="%")
        {
            result=firstnum%secondnum;
            answer=String.format("%.2f", result);
            jTextDisplay.setText(answer);
        }

    }//GEN-LAST:event_jbtnEqualActionPerformed

    private void jbtnDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecActionPerformed
 jTextDisplay.setText(null);
  jTextDisplay.setText("0");
    }//GEN-LAST:event_jbtnDecActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        jTextDisplay.setText(null);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnRndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRndActionPerformed
        // TODO add your handling code here:
         String backspace=null;
        
        if(jTextDisplay.getText().length()>0)
        {
            StringBuilder strB=new StringBuilder(jTextDisplay.getText());
           
            strB.deleteCharAt(jTextDisplay.getText().length()-1);
            backspace=strB.toString();
            jTextDisplay.setText(backspace);
        }


    }//GEN-LAST:event_jbtnRndActionPerformed

    private void jbtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
      firstnum = Double.parseDouble(jTextDisplay.getText());
      jTextDisplay.setText("");
      operation="*";

    }//GEN-LAST:event_jbtnMultActionPerformed

    private void jbtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
      firstnum = Double.parseDouble(jTextDisplay.getText());
      jTextDisplay.setText("");
      operation="/";

    }//GEN-LAST:event_jbtnDivActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
      firstnum = Double.parseDouble(jTextDisplay.getText());
      jTextDisplay.setText("");
      operation="+";

    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMinActionPerformed
        // TODO add your handling code here:
               // TODO add your handling code here:
      firstnum = Double.parseDouble(jTextDisplay.getText());
      jTextDisplay.setText("");
      operation="-";

    }//GEN-LAST:event_jbtnMinActionPerformed

    private void jbtnMouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMouActionPerformed
        // TODO add your handling code here:
        firstnum = Double.parseDouble(jTextDisplay.getText());
      jTextDisplay.setText("");
      operation="%";
    }//GEN-LAST:event_jbtnMouActionPerformed

    private void jbtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConvertActionPerformed
        // TODO add your handling code here:
        double Br_pound=Double.parseDouble(jTextamount.getText());
        
       // Nigerian_Naira=ni;
       
       
        
            if (jCbcountry.getSelectedItem().equals("Nigeria"))
            {
                String cConvert1 = String.format("%.2f",Br_pound *Nigerian_Naira);
               jlblconvert.setText(cConvert1);
               jlblbirr.setText("Naira");
            }
            if(jCbcountry.getSelectedItem().equals("Kenyan"))
            
            {String cConvert2=String.format(" %.2f ",Br_pound*Kenyan_shilling);
                jlblconvert.setText(cConvert2);
                jlblbirr.setText("Shiling");
            }
            
            if(jCbcountry.getSelectedItem().equals("USA"))
            
            {String cConvert3=String.format(" %.2f ",Br_pound*US_Dollar);
                jlblconvert.setText(cConvert3);
                jlblbirr.setText("Dollar");
            }
            
            if(jCbcountry.getSelectedItem().equals("Canada"))
            
            {String cConvert4=String.format(" %.2f ",Br_pound*Canadian_Dollar);
                jlblconvert.setText(cConvert4);
                jlblbirr.setText("Canadian Dollar");
                
            }
            
            
            if(jCbcountry.getSelectedItem().equals("Brazil"))
            
            {String cConvert5=String.format("%.2f ",Br_pound*Brazilian_Real);
                jlblconvert.setText(cConvert5);
                jlblbirr.setText(" Real");
            }
            
            if(jCbcountry.getSelectedItem().equals("Indian"))
            
            {String cConvert6=String.format(" %.2f",Br_pound*Indian_Rupee);
                jlblconvert.setText(cConvert6);
                jlblbirr.setText(" Rupee");
            }
            
        
    }//GEN-LAST:event_jbtnConvertActionPerformed

    private void jCbcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbcountryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCbcountryActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        // TODO add your handling code here:
        jlblconvert.setText(null);
        jTextamount.setText(null);
        jlblbirr.setText("....");
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtncloseActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        // TODO add your handling code here:
     jlblCostOfDelivery.setText("0");
     jlblconvert.setText(null);
     jlblCostOfDelivery.setText("0");
     jlblCostOfDrink.setText("0");
     jlblCostOfMeal.setText("0");
     jlblsubtotal.setText(null);
     jlbltax.setText("0");
     jlbltotal.setText(null);
     jlblCostOfMeal.setText("0");
     jlbltax.setText("0");
     jlblsubtotal.setText(null);
     jtxtbacon.setText("0");
     jtxtburger.setText("0");
     jtxtmeal.setText("0");
     jTextamount.setText(null);
     jtxtchicburg.setText(null);
     jlblbirr.setText("....");
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jCmbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbDrinkActionPerformed
        // TODO add your handling code here:
        
        
       

        if (jCmbDrink.getSelectedItem().equals("Tea"))
        {
            String cTea = String.format("%.2f",Tea);
            jlblCostOfDrink.setText(cTea);
        }
        if (jCmbDrink.getSelectedItem().equals("Ice Tea"))
        {
            String cIce_Tea = String.format("%.2f",Ice_Tea);
            jlblCostOfDrink.setText(cIce_Tea);
        }

        if (jCmbDrink.getSelectedItem().equals("Cofee"))
        {
            String cCoffee = String.format(" %.2f",Coffee);
            jlblCostOfDrink.setText(cCoffee);
        }
        if (jCmbDrink.getSelectedItem().equals("Ice Cofee"))
        {
            String cIce_Coffee= String.format("%.2f",Ice_Coffee);
            jlblCostOfDrink.setText(cIce_Coffee);
        }

        if (jCmbDrink.getSelectedItem().equals("Cola"))
        {
            String cCola = String.format("%.2f",Cola);
            jlblCostOfDrink.setText(cCola);
        }

       
        
         if (jCmbDrink.getSelectedItem().equals("Orange"))
        {
            String cCoke = String.format("%.2f",Orange);
            jlblCostOfDrink.setText(cCoke);
        }
         if (jCmbDrink.getSelectedItem().equals("Milk"))
        {
            String cCoke = String.format("%.2f",Milk);
            jlblCostOfDrink.setText(cCoke);
        }
        

        if (jCmbDrink.getSelectedItem().equals("Select a Drink"))
        {
            //String cIce_Tea = String.format("$ %.2f",Ice_Tea);
            jlblCostOfDrink.setText(null);
        }
        
        
        if (jCmbDrink.getSelectedItem().equals("coke"))
        {
            String cCoke = String.format("%.2f",Coke);
            jlblCostOfDrink.setText(cCoke);
        }
        
    }//GEN-LAST:event_jCmbDrinkActionPerformed

    private void jCDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDeliveryActionPerformed
        // TODO add your handling code here:
       

        if(jCDelivery.isSelected())
        {
            String iDelivery=String.format("%.2f", idelivery);
            jlblCostOfDelivery.setText(iDelivery);

        }
        else
        {
            jlblCostOfDelivery.setText("0");
        }
    }//GEN-LAST:event_jCDeliveryActionPerformed

    private void jcbburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbburgerActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbburgerActionPerformed

    private void jcbburgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbburgerMouseClicked
        // TODO add your handling code here:
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        ChickBurgr= Double.parseDouble(jtxtburger.getText());
        

        
        if(jcbburger.isSelected())
        {
            i[0]=(ChickBurgr*iChiBuurger)+cMeal;
            String pMeal = String.format("%.2f",i[0]);
           jlblCostOfMeal.setText(pMeal);

        }
    }//GEN-LAST:event_jcbburgerMouseClicked

    private void jcbmealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbmealMouseClicked
        // TODO add your handling code here:
        double cMeal=Double.parseDouble(jlblCostOfMeal.getText());
        double BCBurger=Double.parseDouble(jtxtmeal.getText());
       

        if(jcbmeal.isSelected())
        {
            i[1]=(BCBurger*iBCBuurger)+cMeal;
            String pmeal=String.format("%.2f", i[1]);
            jlblCostOfMeal.setText(pmeal);

        }
    }//GEN-LAST:event_jcbmealMouseClicked

    private void jcbcheeseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbcheeseMouseClicked
        // TODO add your handling code here:
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        double cheese= Double.parseDouble(jtxtbacon.getText());
        

        

        if(jcbcheese.isSelected())
        {
            i[2]=(cheese*iCheBuurger)+cMeal;
            String pcheese = String.format("%.2f",i[2]);
           jlblCostOfMeal.setText(pcheese);

        }
    }//GEN-LAST:event_jcbcheeseMouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        // TODO add your handling code here:
        double meal=Double.parseDouble(jlblCostOfMeal.getText());;
        double delivery=Double.parseDouble(jlblCostOfDelivery.getText());
        double drink=Double.parseDouble(jlblCostOfDrink.getText());
        double itax=(meal+delivery+drink)*0.35;
        //itax=itax*0.35;
        String cTax=String.format("%.2f", itax);
        jlbltax.setText(cTax);
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jbtnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnreceiptActionPerformed
        // TODO add your handling code here:
        double qt1=Double.parseDouble(jtxtburger.getText());
        
        double qt3=Double.parseDouble(jtxtmeal.getText());
        
        double qt2=Double.parseDouble(jtxtbacon.getText());
        
        jtxtchicburg.append("\tResturant Managment System:\n\n"+"Chiken Burger:\t\t\t\t"+qt1+" \nChicken Burger meal:\t\t\t"+qt2+"\nBacon and Cheese Burger:\t\t"+qt3+"\nTotal Birr:\t\t\t\t"+itotal+"\n\nThanks for using our Resturant\n\n");
        
        
        
         resutrants n=new resutrants();
         String well="\t\tRessturant Management System ";
         String burgu="Chiken Burger: ";
         String mealu="Chiken Burger meal: ";
         String china="Bacon and Cheese Burger: ";
         String thank="\t Thanks to use our WINAPP";
         
        String burger=jtxtburger.getText();
        String meal=jtxtmeal.getText();
        String bacon=jtxtbacon.getText();
       File account=new File("C:\\Users\\user\\Desktop\\bini\\"+"reciept");
       PrintWriter out = null;
        try {
            out = new PrintWriter(account);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            
        }
          out.println(well);
          out.print(burgu);
          out.println(burger);
          out.print(mealu);
          out.println(meal);
          out.print(china);
          out.println(bacon);
          out.print(thank);
          out.close();
        
        
        
        
    }//GEN-LAST:event_jbtnreceiptActionPerformed

    private void jbtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtntotalActionPerformed

    private void jbtntotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtntotalMouseClicked
        // TODO add your handling code here:
          
         double cTotal1=Double.parseDouble(jlblCostOfDrink.getText());
         double cTotal2=Double.parseDouble(jlblCostOfMeal.getText());
         double cTotal3=Double.parseDouble(jlblCostOfDelivery.getText());
         double cTotal4=Double.parseDouble(jlbltax.getText());
         
         
         
         
         
         
         
         double subTotal =(cTotal1+cTotal2+cTotal3);
         
        
          isubTotal=String.format("%.2f",subTotal);
         jlblsubtotal.setText(isubTotal);
         
         
         double  alltotal =(cTotal1+cTotal2+cTotal3+cTotal4);
          itotal=String .format("%.2f",alltotal);
          jlbltotal.setText(itotal);
         
          /*iTaxTotal=String .format("$ %.2f",cTotal4);
          jlbltax.setText(iTaxTotal);*/
      
    }//GEN-LAST:event_jbtntotalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resutrants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resutrants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resutrants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resutrants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resutrants().setVisible(false);
                new account().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCDelivery;
    private javax.swing.JComboBox<String> jCbcountry;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox<String> jCmbDrink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextDisplay;
    private javax.swing.JTextField jTextamount;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnConvert;
    private javax.swing.JButton jbtnDec;
    private javax.swing.JButton jbtnDiv;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnMin;
    private javax.swing.JButton jbtnMou;
    private javax.swing.JButton jbtnMult;
    private javax.swing.JButton jbtnPoint;
    private javax.swing.JButton jbtnRnd;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnclose;
    private javax.swing.JButton jbtnreceipt;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtntotal;
    private javax.swing.JCheckBox jcbburger;
    private javax.swing.JCheckBox jcbcheese;
    private javax.swing.JCheckBox jcbmeal;
    private javax.swing.JLabel jlblCostOfDelivery;
    private javax.swing.JLabel jlblCostOfDrink;
    private javax.swing.JLabel jlblCostOfMeal;
    private javax.swing.JLabel jlblbirr;
    private javax.swing.JLabel jlblconvert;
    private javax.swing.JLabel jlblsubtotal;
    private javax.swing.JLabel jlbltax;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTextField jtxtbacon;
    private javax.swing.JTextField jtxtburger;
    private javax.swing.JTextArea jtxtchicburg;
    private javax.swing.JTextField jtxtmeal;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    // End of variables declaration//GEN-END:variables
    account q=new account();
    //setcost s=new setcost();
}
