/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setcost_s;
import java.sql.DriverManager;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import login_s.login;

/**
 *
 * @author user
 */
public class setcost extends javax.swing.JFrame {

    Statement stmt=null;
    Connection con=null;
    
    
    public double niger;
    public double canada;
    public double india;
    public double usa;
    
    
    public double tea;
    public double milk;
    public double coffee;
    public double cola;
    
    public double bacon1;
    public double burg;
    public double meal;
    //public double cola;
    
    
    
    
    
    public setcost() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("horses.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jtxtBurger = new javax.swing.JTextField();
        jtxtKitfo = new javax.swing.JTextField();
        jtxtbacon = new javax.swing.JTextField();
        jtxtPizza = new javax.swing.JTextField();
        jtxtTea = new javax.swing.JTextField();
        jtxtMilk = new javax.swing.JTextField();
        jtxtcoffe = new javax.swing.JTextField();
        jtxtCola = new javax.swing.JTextField();
        jtxtNigeria = new javax.swing.JTextField();
        jtxtCanada1 = new javax.swing.JTextField();
        jtxtUSA = new javax.swing.JTextField();
        jtxtIndia = new javax.swing.JTextField();
        jbtnsave1 = new javax.swing.JButton();
        jbtnsave2 = new javax.swing.JButton();
        jbtnsave3 = new javax.swing.JButton();
        jbtnup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Save");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(649, 428));
        setResizable(false);
        getContentPane().setLayout(null);

        jtxtBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBurger.setText("30");
        jtxtBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jtxtBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBurgerActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBurger);
        jtxtBurger.setBounds(130, 100, 80, 36);

        jtxtKitfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtKitfo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtKitfo.setText("60");
        jtxtKitfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtKitfo);
        jtxtKitfo.setBounds(130, 150, 80, 36);

        jtxtbacon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtbacon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtbacon.setText("80");
        jtxtbacon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtbacon);
        jtxtbacon.setBounds(130, 200, 80, 36);

        jtxtPizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtPizza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPizza.setText("50");
        jtxtPizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtPizza);
        jtxtPizza.setBounds(130, 250, 80, 36);

        jtxtTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTea.setText("5");
        jtxtTea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtTea);
        jtxtTea.setBounds(340, 100, 80, 36);

        jtxtMilk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilk.setText("6");
        jtxtMilk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtMilk);
        jtxtMilk.setBounds(340, 150, 80, 36);

        jtxtcoffe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtcoffe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcoffe.setText("3");
        jtxtcoffe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jtxtcoffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcoffeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtcoffe);
        jtxtcoffe.setBounds(340, 200, 80, 36);

        jtxtCola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCola.setText("7");
        jtxtCola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtCola);
        jtxtCola.setBounds(340, 250, 80, 36);

        jtxtNigeria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtNigeria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNigeria.setText("5");
        jtxtNigeria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtNigeria);
        jtxtNigeria.setBounds(560, 100, 80, 36);

        jtxtCanada1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCanada1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCanada1.setText("23");
        jtxtCanada1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtCanada1);
        jtxtCanada1.setBounds(560, 150, 80, 36);

        jtxtUSA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtUSA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtUSA.setText("20");
        jtxtUSA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtUSA);
        jtxtUSA.setBounds(560, 200, 80, 36);

        jtxtIndia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtIndia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtIndia.setText("5");
        jtxtIndia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtIndia);
        jtxtIndia.setBounds(560, 250, 80, 36);

        jbtnsave1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsave1.setText("Save");
        jbtnsave1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsave1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave1);
        jbtnsave1.setBounds(130, 300, 77, 33);

        jbtnsave2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsave2.setText("Save");
        jbtnsave2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsave2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave2);
        jbtnsave2.setBounds(350, 300, 77, 33);

        jbtnsave3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsave3.setText("Save");
        jbtnsave3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnsave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsave3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave3);
        jbtnsave3.setBounds(560, 300, 77, 33);

        jbtnup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnup.setText("FINISH");
        jbtnup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnup);
        jbtnup.setBounds(290, 360, 138, 33);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Upgrade the cost");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, -10, 412, 57);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Meals");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 50, 92, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gurage Kitfo");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(2, 150, 120, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bacon");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 92, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pizza");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 250, 92, 36);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tea");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 100, 92, 36);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Milk");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 150, 92, 36);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Coffee");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 200, 92, 36);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cola");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 250, 92, 36);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nigeria");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 100, 92, 36);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Canada");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 150, 92, 36);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("USA");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 200, 92, 36);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Saudi");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 250, 92, 36);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Burger");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 100, 92, 36);

        jLabel16.setBackground(new java.awt.Color(102, 255, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Drinks");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(280, 50, 92, 36);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Converter");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(480, 50, 130, 36);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, -1, 680, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsave1ActionPerformed
        // TODO add your handling code here:
        double burger=Double.parseDouble(jtxtBurger.getText());
        double kitfo=Double.parseDouble(jtxtKitfo.getText());
        double bacon=Double.parseDouble(jtxtbacon.getText());
        double pizza=Double.parseDouble(jtxtPizza.getText());
        try{
            Class.forName("java.sql.Driver");
            String url="jdbc:mysql://localhost:3306/restaurant";
            String user="root";
            String pwd="";
            Connection con=DriverManager.getConnection(url,user,pwd);
            System.out.println("Successfully conncted");
            String que1="update itemlist set value='"+burger+"' where name='burger'";
            String que2="update itemList set value='"+pizza+"' where name='pizza'";
            String que3="update itemList set value='"+kitfo+"' where name='kitfo'";
            String que4="update itemList set value='"+bacon+"'where name='bacon'";
            
            stmt=con.createStatement();
            stmt.addBatch(que1);
            stmt.addBatch(que2);
            stmt.addBatch(que3);
            stmt.addBatch(que4);
            stmt.executeBatch();
            System.out.println("successfully updated");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(setcost.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(setcost.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jbtnsave1.setVisible(false);
        
    }//GEN-LAST:event_jbtnsave1ActionPerformed

    private void jbtnsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsave2ActionPerformed
        // TODO add your handling code here:
        double Tea=Double.parseDouble(jtxtTea.getText());
        double Milk=Double.parseDouble(jtxtMilk.getText());
        double Coffee=Double.parseDouble(jtxtcoffe.getText());
        double Cola=Double.parseDouble(jtxtCola.getText());
        try{
            Class.forName("java.sql.Driver");
            String url="jdbc:mysql://localhost:3306/restaurant";
            String user="root";
            String pwd="";
            Connection con=DriverManager.getConnection(url,user,pwd);
            System.out.println("Successfully conncted");
            String que1="update itemList set value='"+Tea+"' where name='tea'";
            String que2="update itemList set value='"+Milk+"' where name='Milk'";
            String que3="update itemList set value='"+Coffee+"' where name='Coffee'";
            String que4="update itemList set value='"+Cola+"'where name='Cola'";
            
            stmt=con.createStatement();
            stmt.addBatch(que1);
            stmt.addBatch(que2);
            stmt.addBatch(que3);
            stmt.addBatch(que4);
            stmt.executeBatch();
            System.out.println("successfully updated");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(setcost.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(setcost.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jbtnsave2.setVisible(false);
    }//GEN-LAST:event_jbtnsave2ActionPerformed

    private void jbtnsave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsave3ActionPerformed
        // TODO add your handling code here:
         double Nigeria1=Double.parseDouble(jtxtNigeria.getText());
        double Canada1=Double.parseDouble(jtxtCanada1.getText());
        double USA1=Double.parseDouble(jtxtUSA.getText());
        double India1=Double.parseDouble(jtxtIndia.getText());
        try{
            Class.forName("java.sql.Driver");
            String url="jdbc:mysql://localhost:3306/restaurant";
            String user="root";
            String pwd="";
            Connection con=DriverManager.getConnection(url,user,pwd);
            System.out.println("Successfully conncted");
            String que1="update currency set currency='"+Nigeria1+"' where country='Nigeria'";
            String que2="update currency set currency='"+India1+"' where country='India'";
            String que3="update currency set currency='"+USA1+"' where country='USA'";
            String que4="update currency set currency='"+Canada1+"' where country='Canada'";
            
            stmt=con.createStatement();
            stmt.addBatch(que1);
            stmt.addBatch(que2);
            stmt.addBatch(que3);
            stmt.addBatch(que4);
            stmt.executeBatch();
            System.out.println("successfully updated");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(setcost.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(setcost.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        jbtnsave3.setVisible(false);
    }//GEN-LAST:event_jbtnsave3ActionPerformed

    private void jbtnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupActionPerformed
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jbtnupActionPerformed

    private void jtxtBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBurgerActionPerformed

    private void jtxtcoffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcoffeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcoffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setcost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnsave1;
    private javax.swing.JButton jbtnsave2;
    private javax.swing.JButton jbtnsave3;
    private javax.swing.JButton jbtnup;
    public javax.swing.JTextField jtxtBurger;
    public javax.swing.JTextField jtxtCanada1;
    public javax.swing.JTextField jtxtCola;
    public javax.swing.JTextField jtxtIndia;
    public javax.swing.JTextField jtxtKitfo;
    public javax.swing.JTextField jtxtMilk;
    public javax.swing.JTextField jtxtNigeria;
    public javax.swing.JTextField jtxtPizza;
    public javax.swing.JTextField jtxtTea;
    public javax.swing.JTextField jtxtUSA;
    public javax.swing.JTextField jtxtbacon;
    public javax.swing.JTextField jtxtcoffe;
    // End of variables declaration//GEN-END:variables
    
}
