/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package setcost_s;
import resutrant_s.resutrants;

/**
 *
 * @author user
 */
public class setcost extends javax.swing.JFrame {

    /**
     * Creates new form setcost
     */
    
    public double niger;
    public double canada;
    public double india;
    public double usa;
    
    
    public double tea;
    public double milk;
    public double coffee;
    public double cola;
    
    public double burg;
    public double meal;
    public double bacon;
    //public double cola;
    
    
    
    
    
    public setcost() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jtxtburg = new javax.swing.JTextField();
        jtxtm = new javax.swing.JTextField();
        jtxtbacon = new javax.swing.JTextField();
        jtxtarosto = new javax.swing.JTextField();
        jtxttea = new javax.swing.JTextField();
        jtxtmilk = new javax.swing.JTextField();
        jtxtcoffe = new javax.swing.JTextField();
        jtxtcola = new javax.swing.JTextField();
        jtxtn = new javax.swing.JTextField();
        jtxtc = new javax.swing.JTextField();
        jtxtusa = new javax.swing.JTextField();
        jtxti = new javax.swing.JTextField();
        jbtnsave1 = new javax.swing.JButton();
        jbtnsave2 = new javax.swing.JButton();
        jbtnsave3 = new javax.swing.JButton();
        jbtnup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Save");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(685, 410));
        setResizable(false);
        getContentPane().setLayout(null);

        jtxtburg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtburg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtburg.setText("30");
        jtxtburg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jtxtburg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtburgActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtburg);
        jtxtburg.setBounds(120, 100, 80, 36);

        jtxtm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtm.setText("60");
        jtxtm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtm);
        jtxtm.setBounds(120, 150, 80, 36);

        jtxtbacon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtbacon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtbacon.setText("80");
        jtxtbacon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtbacon);
        jtxtbacon.setBounds(120, 200, 80, 36);

        jtxtarosto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtarosto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtarosto.setText("50");
        jtxtarosto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtarosto);
        jtxtarosto.setBounds(120, 250, 80, 36);

        jtxttea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxttea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttea.setText("5");
        jtxttea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxttea);
        jtxttea.setBounds(340, 100, 80, 36);

        jtxtmilk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtmilk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtmilk.setText("6");
        jtxtmilk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtmilk);
        jtxtmilk.setBounds(340, 150, 80, 36);

        jtxtcoffe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtcoffe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcoffe.setText("3");
        jtxtcoffe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtcoffe);
        jtxtcoffe.setBounds(340, 200, 80, 36);

        jtxtcola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtcola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcola.setText("7");
        jtxtcola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtcola);
        jtxtcola.setBounds(340, 250, 80, 36);

        jtxtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtn.setText("5");
        jtxtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtn);
        jtxtn.setBounds(560, 100, 80, 36);

        jtxtc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtc.setText("23");
        jtxtc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtc);
        jtxtc.setBounds(560, 150, 80, 36);

        jtxtusa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtusa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtusa.setText("20");
        jtxtusa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxtusa);
        jtxtusa.setBounds(560, 200, 80, 36);

        jtxti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxti.setText("5");
        jtxti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jtxti);
        jtxti.setBounds(560, 250, 80, 36);

        jbtnsave1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsave1.setText("Save");
        jbtnsave1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsave1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave1);
        jbtnsave1.setBounds(130, 300, 77, 33);

        jbtnsave2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsave2.setText("Save");
        jbtnsave2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnsave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsave2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave2);
        jbtnsave2.setBounds(350, 300, 77, 33);

        jbtnsave3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnsave3.setText("Save");
        jbtnsave3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnsave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsave3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave3);
        jbtnsave3.setBounds(580, 310, 77, 33);

        jbtnup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnup.setText("Upgrade");
        jbtnup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnup);
        jbtnup.setBounds(350, 350, 138, 33);

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Upgrade the cost");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, -10, 412, 57);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Meals");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 50, 92, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Meal");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 92, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bacon");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 200, 92, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pizza");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 250, 92, 36);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tea");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 100, 92, 36);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Milk");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 150, 92, 36);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Coffee");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 200, 92, 36);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cola");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 250, 92, 36);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nigeria");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 100, 92, 36);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Canada");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 150, 92, 36);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("USA");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 200, 92, 36);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Indian");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 250, 92, 36);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Burger");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 100, 92, 36);

        jLabel16.setBackground(new java.awt.Color(102, 255, 102));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Drinks");
        jLabel16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(280, 50, 92, 36);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Converter");
        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(480, 50, 130, 36);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setcost_s/past.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 680, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsave1ActionPerformed
        // TODO add your handling code here:
        jbtnsave1.setVisible(false);
        
    }//GEN-LAST:event_jbtnsave1ActionPerformed

    private void jbtnsave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsave2ActionPerformed
        // TODO add your handling code here:
        jbtnsave2.setVisible(false);
    }//GEN-LAST:event_jbtnsave2ActionPerformed

    private void jbtnsave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsave3ActionPerformed
        // TODO add your handling code here:
        jbtnsave3.setVisible(false);
    }//GEN-LAST:event_jbtnsave3ActionPerformed

    private void jbtnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupActionPerformed
        // TODO add your handling code here:
        resutrants r=new resutrants();
        
        
        r.Nigerian_Naira=Double.parseDouble(jtxtn.getText());
        niger=r.Nigerian_Naira;
        
         r.Canadian_Dollar=Double.parseDouble(jtxtc.getText());
        canada=r.Canadian_Dollar;
        
        
         r.Indian_Rupee=Double.parseDouble(jtxti.getText());
        niger=r.Indian_Rupee;
        
        
         r.US_Dollar=Double.parseDouble(jtxtusa.getText());
        niger=r.Nigerian_Naira;
        
        
        //cost for Drink
        
         r.Tea=Double.parseDouble(jtxttea.getText());
         tea=r.Tea;
        
         r.Milk=Double.parseDouble(jtxtmilk.getText());
        milk=r.Milk;
        
        
         r.Coffee=Double.parseDouble(jtxtcoffe.getText());
        coffee=r.Coffee;
        
        
         r.Cola=Double.parseDouble(jtxtusa.getText());
        cola=r.Cola;
        
        
        //cost for meal
        
        
        
        r.iChiBuurger=Double.parseDouble(jtxtburg.getText());
         burg=r.iChiBuurger;
        
         r.iBCBuurger=Double.parseDouble(jtxtm.getText());
         meal=r.iBCBuurger;
        
        
         r.iCheBuurger=Double.parseDouble(jtxtbacon.getText());
         bacon=r.iCheBuurger;
        
        
        
        
        
        
        
        
        
        
        
        this.setVisible(false);
        //niger=jtxtn.getText();
        r.setVisible(true);
        System.out.println(r.Nigerian_Naira);
        
    }//GEN-LAST:event_jbtnupActionPerformed

    private void jtxtburgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtburgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtburgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setcost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setcost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnsave1;
    private javax.swing.JButton jbtnsave2;
    private javax.swing.JButton jbtnsave3;
    private javax.swing.JButton jbtnup;
    public javax.swing.JTextField jtxtarosto;
    public javax.swing.JTextField jtxtbacon;
    public javax.swing.JTextField jtxtburg;
    public javax.swing.JTextField jtxtc;
    public javax.swing.JTextField jtxtcoffe;
    public javax.swing.JTextField jtxtcola;
    public javax.swing.JTextField jtxti;
    public javax.swing.JTextField jtxtm;
    public javax.swing.JTextField jtxtmilk;
    public javax.swing.JTextField jtxtn;
    public javax.swing.JTextField jtxttea;
    public javax.swing.JTextField jtxtusa;
    // End of variables declaration//GEN-END:variables
    
}
