/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package account_s;
import login_s.login;
import setcost_s.setcost;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */

public class account extends javax.swing.JFrame {

    /**
     * Creates new form account
     */
    public account() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("horses.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jtxtname1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jpsd3 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jpsd2 = new javax.swing.JPasswordField();
        jlblpass = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtncreate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jtxtPosition = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("create an account");
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(450, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("create An Account ");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(40, 10, 360, 40);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, -2, 550, 80);

        jDesktopPane2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Name");
        jDesktopPane2.add(jLabel2);
        jLabel2.setBounds(20, 10, 119, 46);

        jtxtname1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jDesktopPane2.add(jtxtname1);
        jtxtname1.setBounds(180, 10, 146, 46);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password");
        jDesktopPane2.add(jLabel1);
        jLabel1.setBounds(20, 60, 120, 46);

        jpsd3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpsd3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpsd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpsd3ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jpsd3);
        jpsd3.setBounds(180, 60, 146, 46);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirm Password");
        jDesktopPane2.add(jLabel4);
        jLabel4.setBounds(10, 110, 164, 46);

        jpsd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpsd2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jpsd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpsd2ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jpsd2);
        jpsd2.setBounds(180, 110, 146, 46);
        jDesktopPane2.add(jlblpass);
        jlblpass.setBounds(340, 110, 190, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("   Position");
        jDesktopPane2.add(jLabel5);
        jLabel5.setBounds(10, 170, 160, 30);

        jbtncreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtncreate.setText("create");
        jbtncreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncreateActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jbtncreate);
        jbtncreate.setBounds(300, 230, 130, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Logout");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton1);
        jButton1.setBounds(30, 230, 110, 40);

        jtxtPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "manager", "cashier" }));
        jtxtPosition.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jDesktopPane2.add(jtxtPosition);
        jtxtPosition.setBounds(180, 160, 150, 40);

        getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(0, 89, 550, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncreateActionPerformed
        // TODO add your handling code here:
        setcost n=new setcost();
        
        String password=jpsd3.getText();
        String name=jtxtname1.getText();
        String cpassword=jpsd2.getText();
        String position=(String)jtxtPosition.getSelectedItem();
        String message="password has not been matched-RE-ENNTER!";
        
        try{
            Class.forName("java.sql.Driver");
            String url="jdbc:mysql://localhost:3306/restaurant";
            String user="root";
            String pwd="";
            Connection con=DriverManager.getConnection(url,user,pwd);
            System.out.println("Successfully connected");
            Statement st=con.createStatement();
             if(password.equals(cpassword)){
            String que="insert into login values('"+name+"','"+password+"','"+position+"')";
            st.execute(que);
                System.out.println("Successfully inserted");
            JOptionPane.showMessageDialog(null,"You have successfully created new account");
            jpsd3.setText("");
            jtxtname1.setText("");
            jpsd2.setText("");
            //jtxtPosition.setText("");
            }
            else{
             JOptionPane.showMessageDialog(null, message);
               jpsd3.setText("");
            jpsd2.setText("");
            
            }
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.toString());
        } catch (SQLException ex) {
            Logger.getLogger(account.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
        
       /*File account=new File("C:\\bush\\"+name);
       PrintWriter out = null;
        try {
            out = new PrintWriter(account);
            if(password.equals(cpassword))
                //this.setVisible(true);
               // jlblpass.setText("password");
            {
                out.println(name);
            out.println(password);
            out.close();
            this.setVisible(false);
            n.setVisible(true);
             
            }
            
            else
                jlblpass.setText("password never much");
            //cpassword=password;
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            
        }
       */
         
          
    }//GEN-LAST:event_jbtncreateActionPerformed
   
           
        
        
  
    private void jpsd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpsd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsd2ActionPerformed

    private void jpsd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpsd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpsd3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JButton jbtncreate;
    private javax.swing.JLabel jlblpass;
    private javax.swing.JPasswordField jpsd2;
    private javax.swing.JPasswordField jpsd3;
    private javax.swing.JComboBox<String> jtxtPosition;
    private javax.swing.JTextField jtxtname1;
    // End of variables declaration//GEN-END:variables
    
}
