/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package account_s;
import login_s.login;
import setcost_s.setcost;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import resutrant_s.resutrants;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author user
 */

public class account extends javax.swing.JFrame {

    /**
     * Creates new form account
     */
    public account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jbtncreate = new javax.swing.JButton();
        jpsd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpsd1 = new javax.swing.JPasswordField();
        jlblpass = new javax.swing.JLabel();
        jbtnacc = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("create an account");
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(43, 147, 164, 46);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(88, 95, 119, 46);

        jtxtname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jtxtname);
        jtxtname.setBounds(225, 95, 146, 46);

        jbtncreate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtncreate.setText("create");
        jbtncreate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncreateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtncreate);
        jbtncreate.setBounds(290, 260, 81, 37);

        jpsd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpsd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jpsd);
        jpsd.setBounds(225, 150, 146, 46);

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("create An Account ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 360, 47);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(43, 202, 164, 46);

        jpsd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpsd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(jpsd1);
        jpsd1.setBounds(225, 205, 146, 46);

        jlblpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblpass.setForeground(new java.awt.Color(204, 0, 0));
        jlblpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlblpass);
        jlblpass.setBounds(190, 50, 180, 31);

        jbtnacc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnacc.setText("Have Account");
        jbtnacc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jbtnacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaccActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnacc);
        jbtnacc.setBounds(93, 260, 155, 37);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account_s/Rainbow Splash_146.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 540, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncreateActionPerformed
        // TODO add your handling code here:
        setcost n=new setcost();
        String password=jpsd.getText();
        String name=jtxtname.getText();
        String cpassword=jpsd1.getText();
        String message="SORRY YOUR PASSWORD DON'T MUCH!";
        
       File account=new File("C:\\Users\\user\\Desktop\\bini\\"+name);
       PrintWriter out = null;
        try {
            out = new PrintWriter(account);
            if(password.equals(cpassword))
                //this.setVisible(true);
               // jlblpass.setText("password");
            {
                out.println(name);
            out.println(password);
            out.close();
            this.setVisible(false);
            n.setVisible(true);
             
            }
            
            else
                jlblpass.setText("password never much");
            //cpassword=password;
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            
        }
       
         
          
    }//GEN-LAST:event_jbtncreateActionPerformed
   
           
        
        
  
    private void jbtnaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaccActionPerformed
        // TODO add your handling code here:
        login m=new login();
        this.setVisible(false);
        m.setVisible(true);
        
    }//GEN-LAST:event_jbtnaccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnacc;
    public javax.swing.JButton jbtncreate;
    private javax.swing.JLabel jlblpass;
    private javax.swing.JPasswordField jpsd;
    private javax.swing.JPasswordField jpsd1;
    private javax.swing.JTextField jtxtname;
    // End of variables declaration//GEN-END:variables
    
}
